site_name: Kubernetes Gateway API
repo_url: https://github.com/kubernetes-sigs/gateway-api
repo_name: kubernetes-sigs/gateway-api
site_dir: site
docs_dir: site-src
extra_css:
  - stylesheets/extra.css
hooks:
- hack/mkdocs-copy-geps.py
watch:
- geps
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/logo/logo-text-large-horizontal-white.png
  favicon: images/k8s-favicon.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.top
    - navigation.expand
  palette:
    primary: custom
  custom_dir: site-src/overrides
edit_uri: edit/main/site-src/
plugins:
  - search
  - awesome-pages
  - macros:
      include_dir: examples
      j2_line_comment_prefix: "#$"
  - redirects:
      redirect_maps:
        'guides/getting-started.md': 'guides/index.md'
        'concepts/gamma.md': 'mesh/index.md'
        'concepts/service-facets.md': 'mesh/service-facets.md'
        'concepts/guidelines.md': 'guides/api-design.md'
        'contributing/community.md': 'contributing/index.md'
        'contributing/gamma.md': 'mesh/index.md#contributing'
        'reference/implementers-guide.md': 'guides/implementers.md'
        'references/implementers-guide.md': 'guides/implementers.md'
        'references/spec.md': 'reference/spec.md'
        'references/policy-attachment.md': 'reference/policy-attachment.md'
  - mermaid2
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - toc:
      permalink: true
  - tables
nav:
  - 概览:
    - 介绍: index.md
    - 概念:
        API概览: concepts/api-overview.md
        Conformance: concepts/conformance.md
        Roles and Personas: concepts/roles-and-personas.md
        安全模型: concepts/security-model.md
        用户案例: concepts/use-cases.md
        版本: concepts/versioning.md
    - 服务网格:
        概览: mesh/index.md
        GAMMA Initiative: mesh/gamma.md
        Service Facets: mesh/service-facets.md
    - 实现相关: implementations.md
    - 常见问题: faq.md
    - 词汇表: concepts/glossary.md
  - Guides:
    - 用户指南:
      - 开始入门: guides/index.md
      - 简易Gateway: guides/simple-gateway.md
      - HTTP路由: guides/http-routing.md
      - HTTP redirects and rewrites: guides/http-redirect-rewrite.md
      - HTTP头修改器: guides/http-header-modifier.md
      - HTTP流量splitting: guides/traffic-splitting.md
      - Cross-Namespace路由: guides/multiple-ns.md
      - TLS: guides/tls.md
      - TCP路由: guides/tcp.md
      - gRPC路由: guides/grpc-routing.md
      - 从Ingress迁移: guides/migrating-from-ingress.md
      - Backend Protocol Selection: guides/backend-protocol.md
    - API设计: guides/api-design.md
    - CRD管理: guides/crd-management.md
    - Implementer's Guide: guides/implementers.md
  - 参考引用:
    - API Types:
      - Gateway: api-types/gateway.md
      - GatewayClass: api-types/gatewayclass.md
      - GRPCRoute: api-types/grpcroute.md
      - HTTPRoute: api-types/httproute.md
      - Policy:
        - BackendTLSPolicy: api-types/backendtlspolicy.md
      - ReferenceGrant: api-types/referencegrant.md
    - API specification: reference/spec.md
    - Policy Attachment: reference/policy-attachment.md
  - Enhancements:
    - 概览: geps/overview.md
    - Provisional:
      - geps/gep-91/index.md
      - geps/gep-1619/index.md
      - geps/gep-1651/index.md
      - geps/gep-1867/index.md
    # - Implementable:
    #   -
    - Experimental:
      - geps/gep-713/index.md
      - geps/gep-957/index.md
      - geps/gep-1016/index.md
      - geps/gep-1426/index.md
      - geps/gep-1686/index.md
      - geps/gep-1709/index.md
      - geps/gep-1742/index.md
      - geps/gep-1748/index.md
      - geps/gep-1762/index.md
      - geps/gep-1897/index.md
      - geps/gep-1911/index.md
      - geps/gep-2162/index.md
      - geps/gep-2257/index.md
    - Standard:
      - geps/gep-709/index.md
      - geps/gep-718/index.md
      - geps/gep-724/index.md
      - geps/gep-726/index.md
      - geps/gep-746/index.md
      - geps/gep-820/index.md
      - geps/gep-851/index.md
      - geps/gep-1323/index.md
      - geps/gep-1364/index.md
    - Memorandum:
      - geps/gep-917/index.md
      - geps/gep-922/index.md
      - geps/gep-1324/index.md
      - geps/gep-2659/index.md
    - Declined:
      - geps/gep-735/index.md
      - geps/gep-1282/index.md
  - Contributing:
    - How to Get Involved: contributing/index.md
    - Developer Guide: contributing/devguide.md
    - Documentation Style Guide: contributing/style-guide.md
    - Enhancement Requests: contributing/enhancement-requests.md
    - Contributor Ladder: contributing/contributor-ladder.md
